/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 02-02-2020 18:17:59 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS seq_account
;

DROP SEQUENCE IF EXISTS seq_account_pair
;

/* Drop Tables */

DROP TABLE IF EXISTS account CASCADE
;

DROP TABLE IF EXISTS account_pair CASCADE
;

/* Create Tables */

CREATE TABLE account
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('seq_account'::text)::regclass),
	name varchar(50) NOT NULL,
	address varchar(100) NOT NULL,
	pwd varchar(100) NOT NULL
)
;

CREATE TABLE account_pair
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('seq_account_pair'::text)::regclass),
	account_id_left bigint NOT NULL,
	account_id_right bigint NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE account ADD CONSTRAINT "PK_account"
	PRIMARY KEY (id)
;

CREATE UNIQUE INDEX "IX_account_hash" ON account (address ASC)
;

ALTER TABLE account_pair ADD CONSTRAINT "PK_account_pair"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_account_pair_account" ON account_pair (account_id_left ASC)
;

CREATE INDEX "IXFK_account_pair_account_02" ON account_pair (account_id_right ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE account_pair ADD CONSTRAINT "FK_account_pair_account"
	FOREIGN KEY (account_id_left) REFERENCES account (id) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE account_pair ADD CONSTRAINT "FK_account_pair_account_02"
	FOREIGN KEY (account_id_right) REFERENCES account (id) ON DELETE Cascade ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE seq_account INCREMENT 1 START 1
;

COMMENT ON TABLE account_pair
	IS 'Binds two accounts together to form testing pair.'
;

CREATE SEQUENCE seq_account_pair INCREMENT 1 START 1
;
